# Add this to your main docker-compose.yml file

  soniox-vapi-transcriber:
    image: soniox-vapi-transcriber:latest
    container_name: soniox-vapi-transcriber
    restart: unless-stopped
    environment:
      # Soniox API Key (required)
      - SONIOX_API_KEY=${SONIOX_API_KEY}

      # Server configuration
      - VAPI_SERVER_HOST=0.0.0.0
      - VAPI_SERVER_PORT=8080

      # Nginx Proxy Configuration
      - VIRTUAL_HOST=transcriber.techvantage.es
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=transcriber.techvantage.es
      - LETSENCRYPT_EMAIL=florin.botis@gmail.com

    networks:
      - webproxy

    # Health check
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8080/health')\" || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
