version: '3.8'

services:
  soniox-vapi-server:
    build: .
    container_name: soniox-vapi-transcriber
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Soniox API Key (required)
      - SONIOX_API_KEY=${SONIOX_API_KEY}

      # Server configuration (optional)
      - VAPI_SERVER_HOST=0.0.0.0
      - VAPI_SERVER_PORT=8080

    # Resource limits (optional - adjust based on your VPS)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
